name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-desktop:
    name: Build Avalonia App (Desktop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Clean Project
        run: dotnet clean ./src/AvaloniaApp

      - name: Restore dependencies
        run: dotnet restore ./src/AvaloniaApp --verbosity minimal 2>&1 | tee restore-log.txt

      - name: Build Avalonia App with Verbose Logging
        run: |
          dotnet build ./src/AvaloniaApp --configuration Release --no-restore --verbosity detailed 2>&1 | tee build-log.txt
          if [ $? -ne 0 ]; then
            echo "Build failed. Check build-log.txt for details."
            exit 1
          fi
          echo "Checking output directory..."
          ls -la ./src/AvaloniaApp/bin/Release/net7.0/
          if [ $? -ne 0 ]; then
            echo "Build output not found."
            exit 1
          fi

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AvaloniaApp-Build
          path: ./src/AvaloniaApp/bin/Release/net7.0/*
          if-no-files-found: error

      - name: Run Unit Tests (if any)
        run: |
          dotnet test ./src/AvaloniaApp --no-build --verbosity minimal 2>&1 | tee test-log.txt
          if [ $? -ne 0 ]; then
            echo "Unit tests failed. Check test-log.txt for details."
            exit 1
          fi
