name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-desktop:
    name: Build Avalonia App (Desktop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Clean Project
        run: dotnet clean ./src/AvaloniaApp

      - name: Restore dependencies
        run: dotnet restore ./src/AvaloniaApp --verbosity minimal 2>&1 | tee restore-log.txt

      - name: Build Avalonia App
        run: |
          dotnet build ./src/AvaloniaApp --configuration Release --no-restore --verbosity minimal 2>&1 | tee build-log.txt
          if [ $? -ne 0 ]; then
            echo "Build failed. Check build-log.txt for details."
            exit 1
          fi

      - name: Run Unit Tests (if any)
        run: |
          dotnet test ./src/AvaloniaApp --no-build --verbosity minimal 2>&1 | tee test-log.txt
          if [ $? -ne 0 ]; then
            echo "Unit tests failed. Check test-log.txt for details."
            exit 1
          fi

  build-mobile:
    name: Build MAUI App (Mobile)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Clean Project
        run: dotnet clean ./src/MAUIApp

      - name: Restore dependencies
        run: dotnet restore ./src/MAUIApp --verbosity minimal 2>&1 | tee restore-log.txt

      - name: Build MAUI App (Android)
        run: |
          dotnet build ./src/MAUIApp --configuration Release --no-restore --verbosity minimal 2>&1 | tee build-log.txt
          if [ $? -ne 0 ]; then
            echo "Build failed. Check build-log.txt for details."
            exit 1
          fi

      - name: Run Unit Tests (if any)
        run: |
          dotnet test ./src/MAUIApp --no-build --verbosity minimal 2>&1 | tee test-log.txt
          if [ $? -ne 0 ]; then
            echo "Unit tests failed. Check test-log.txt for details."
            exit 1
          fi
